### ISSUE TITLE
Unable to import Vi-Module with class errors

### ISSUE THREAD

**Issue by smbasha27** [rgel/PowerCLi#14]
Please the screenshot below

![image](https://user-images.githubusercontent.com/20731359/51504827-d4032d00-1e47-11e9-95fe-371c45af9093.png)

**Comment by rgel** [comment]
Please use [these](https://github.com/rgel/PowerCLi/tree/master/Vi-Module) **instructions & requirements** to import the module

**Comment by smbasha27** [comment]
Thanks, works great
