### ISSUE TITLE
error when importing module

### ISSUE THREAD

**Issue by lorriEDw** [rgel/PowerCLi#4]
I am using VMware vSphere PowerCLI6.0 Release 3 and copied the Vi-Module to the modules folder 
ProgramFiles(x86)/VMware/Infrastructure/vSpherePowerCLI/Modules
when I run the Import-Module Vi-Module -Force -Verbose I get the attached errors - should this work with powercli? or am I missing something?
Thanks

![screen shot 2017-10-17 at 2 11 37 pm](https://user-images.githubusercontent.com/28764879/31681676-f556c6ba-b345-11e7-88f3-db327a526d38.png)

**Comment by rgel** [comment]
Check the $PSVersionTable variable, you have to upgrade the PowerShell to
V5 or remove ", Vi-Sdrs.ps1" from Vi-Module.psd1 file and lose SDRS related
functions.
The choice is yours.


https://ps1code.com

**Comment by prisoner107** [comment]
Duplicate Issue. Using PS Version 5.1, also removed Vi-Sdrs.ps1 script. Does not seem to matter, seems there is a valid error in the Expand-VMGuestPartition Function.

![vi-moduleerror](https://user-images.githubusercontent.com/33638117/32747209-0669ac88-c886-11e7-813b-24b3a9497ff2.png)

**Comment by rgel** [comment]
It seems you had Copy-Pasted the RAW file from Github, try `Clone or download` button from the <a href="https://github.com/rgel/PowerCLi" target="_blank" rel="noopener noreferrer">main</a> PowerCLi repo page.

**Comment by prisoner107** [comment]
The download was taken from the main PowerCLi page. But you gave me another idea to copy-paste from the RAW file from Github. That worked, the code is error free. Thanks.

**Comment by rgel** [comment]
Happy scripting

https://ps1code.com

**Comment by tikondrus** [comment]
![powershell_2017-12-20_11-12-24](https://user-images.githubusercontent.com/34535914/34200326-5ad7f760-e579-11e7-85a4-6a793974e022.png)

**Comment by tikondrus** [comment]
without  Vi-Sdrs.ps1
![powershell_2017-12-20_11-32-42](https://user-images.githubusercontent.com/34535914/34200384-9198d026-e579-11e7-9f25-5d40b2faa24f.png)

**Comment by tikondrus** [comment]
If I had Copy-Pasted the RAW file from Github import module had been done.

**Comment by rgel** [comment]
This is known issue, sometimes files would be damaged while downloading from the GitHub :-(
There are two download methods: copy-paste raw files or download a whole repository zip file
![image 007](https://user-images.githubusercontent.com/6964549/34210557-f2a4178e-e59e-11e7-84ff-11b35bfd38bc.png)
![image 008](https://user-images.githubusercontent.com/6964549/34210558-f2d4ab9c-e59e-11e7-9de5-ee5ed2bdc3c1.png)
The reason is your enterprise proxy or antivirus software.
Try to use different download method or download outside your organization.

**Comment by janxster** [comment]
I found that in Vi-Module.psm1 there was a  ANSI character â€“ that is displayed as - in UTF-8 encoding in 3 places. Once I replaced â€“ with - it worked as expected.
