### ISSUE TITLE
Import-Module issue with GetVlan ValidateRange

### ISSUE THREAD

**Issue by cfmorrell** [rgel/PowerCLi#6]
On execution of Import-Module Vi-Module -Force -Verbose, an error with ValidateRange is raised and stops import.

![capture](https://user-images.githubusercontent.com/6538191/38164894-62964808-34d9-11e8-8b4f-35653d8f58f8.PNG)

**Comment by rgel** [comment]
Probably the reason is PowerShell v5.1 and above. Try for now to edit the `Vi-Module.psm1` file and remove `[ValidateRange(1, 4094)]` from row 41.
I will be looking for the solution.

**Comment by cfmorrell** [comment]
Thank you.  That did work as a workaround.
